name: Docker Image CI
on:
  push:
    branches: [ el5-main ]
  pull_request:
    branches: [ el5-main ]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maisuier/mastodon
          tags: ${{ github.event.release.tag_name }}